### ISSUE TITLE
Add placeholder to Config

### ISSUE THREAD

**Issue by slissner** [abadi199/intl-phone-input#12]
It would be nice to add a placeholder field to the Config type and then render the `placeholder` attribute accordingly. 👍

**Comment by slissner** [comment]
I discovered `IntlPhoneInput.customInput` with which I think I can solve the issue.

**Comment by slissner** [comment]
Well, it seems that the following function does not work properly:

```elm
customInput : List (Attribute msg) -> Config msg -> State -> PhoneNumber -> Html.Html msg
customInput attributes config state phoneNumber =
    customInputStyled attributes config state phoneNumber
        |> Html.Styled.toUnstyled
```

I am receiving the following compiler error:

```
The 1st argument to `customInput` is not what I expect:

408|>                        IntlPhoneInput.customInput [ placeholder <| session.getPhrase Lang.PhoneNumber ]
409|                             phoneCfg
410|                             (Tuple.first model.phoneNumber)
411|                             (Tuple.second model.phoneNumber)

This argument is a list of type:

    List (Attribute msg)

But `customInput` needs the 1st argument to be:

    List (Html.Styled.Attribute msg)
Detected errors in 1 module.            
```

**Comment by adrian2monk** [comment]
Do you can recommend other alternative? I also need to set a default flag and I couldn't find any way to do that 😢 .

**Comment by cmarfia** [comment]
Hello @slissner @adrian2monk,

Before I look more into this can you help me confirm what you are wanting to do?

I want to make sure I am properly helping you. 

### My understanding:

You are looking to render the `tel` input with a placeholder attribute that you can control.

For example: 
```
<input type="tel" placeholder=" (xxx) xxx-xxxx ">
```

If that is the case please take a look at this updated example here on ellie: https://ellie-app.com/cpjVJ9CcYB7a1

If not, lets talk more about what you are looking for.

**Comment by cmarfia** [comment]
@adrian2monk, I just saw the second part of your question so my apologies for ignoring it. 

If you are wanting a "flag" or country to be selected by default you would need to have the default state have the `isoCode` populated to something. 

For example if we use the demo from the ellie link above, we would just need to change line 26 to have a isoCode set.
```
initialModel : Model
initialModel =
    { homePhoneNumber = ( IntlPhoneInput.initialState, { isoCode = "US", phoneNumber = "" } )
    }
```
> This will make the United States be the defaulted country.

**Comment by cmarfia** [comment]
Closing due to no response. 

If there is an issue please re-open.
